node {
    def WORKSPACE = "/var/lib/jenkins/workspace/"
    def dockerImageTag = "star-bank/authorization-microservice"

    try {
        notifyBuild('STARTED')
        stage('check-repository-clone') {
            sh "ls -l"
        }
    } catch(e) {
        currentBuild.result = "FAILED"
        throw e
    } finally {
        notifyBuild(currentBuild.result)
    }
}