pipeline {
    agent any
    environment {
        PROJECT_NAME="star-bank-authorization-microservice"
        VERSION="0.0.1"
    }
    stages {
        stage('clone-repository-stage') {
            try {
                steps {
                    echo "Repository successfully cloned. For project: ${PROJECT_NAME}"
                    sh "ls -l"
                }
            } catch (exception) {
                currentBuild.result = "FAILED"
                throw exception
            } finally {
                notifyBuild(currentBuild.result)
            }
        }
        stage('build-stage') {
            try {
                steps {
                    sh "ls -l"
                    sh "docker --version"
                    sh "docker image ls"
                }
            } catch (exception) {
                currentBuild.result = "FAILED"
                throw exception
            } finally {
                notifyBuild(currentBuild.result)
            }
        }
    }
}