pipeline {
    agent any
    environment {
        PROJECT_NAME="star-bank-authorization-microservice"
        VERSION="0.0.1"
    }
    stages {
        stage('clone-repository-stage') {
            steps {
                echo "Repository successfully cloned. For project: ${PROJECT_NAME}"
                sh "ls -l"
            }
        }
        stage('build-stage') {
            steps {
                sh "ls -l"
                sh "docker --version"
                sh "docker image ls"
            }
        }
    }
}